In [4]:
from tensorflow import keras
from tensorflow.keras.preprocessing import image
import numpy as np

In [2]:
model = keras.models.load_model('1JuneClassification')

In [3]:
val_dir = "output/val"
test_images = ["/50K-samples/30.jpg","/50K-samples/84.jpg","/50K-samples/50.jpg",
               "/10K-samples/58.jpg","/10K-samples/105.jpg","/10K-samples/73.jpg",
               "/100K-samples/121.jpg","/100K-samples/80.jpg","/100K-samples/100.jpg",
               ]

In [5]:

for image_path in test_images:
    path = val_dir+image_path
    img = image.load_img(path, target_size=(150,150))
    # imgplot = plt.imshow(img)
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)

    images = np.vstack([x])
    classes = model.predict(images, batch_size=10)

    # print(fn)
    print(classes)
    if classes[0][0]==1:
        print('100k')
    elif classes[0][1]==1:
        print('10k')
    elif classes[0][2]==1:
        print('50k')

[[0. 0. 1.]]
50k
[[0. 0. 1.]]
50k
[[0. 0. 1.]]
50k
[[0. 1. 0.]]
10k
[[0. 1. 0.]]
10k
[[0. 1. 0.]]
10k
[[1. 0. 0.]]
100k
[[1. 0. 0.]]
100k
[[1. 0. 0.]]
100k
